# Generated by Django 5.2.9 on 2026-02-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='product_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
