# Generated by Django 5.2.9 on 2026-02-12 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_business_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='product_attributes',
        ),
    ]
