# Generated by Django 5.2.9 on 2026-03-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Приход (Поставка)'), ('SALE', 'Продажа'), ('RETURN', 'Возврат от клиента'), ('LOSS', 'Списание/Брак')], max_length=20),
        ),
    ]
