# Generated by Django 5.2.9 on 2026-03-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_category_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Это услуга (не требует склада)'),
        ),
    ]
