# Generated by Django 5.2.9 on 2026-03-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_service',
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_service',
            field=models.BooleanField(default=False, help_text='Все позиции в этом шаблоне будут услугами'),
        ),
    ]
