# Generated by Django 5.2.9 on 2026-03-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_is_service_producttype_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
    ]
